/**
 * SSE message endpoint — `POST /gateways/:name/sessions/:id/messages`.
 *
 * Streams turn / heartbeat / done / error events generated by the gateway's
 * adapter. Supports `Last-Event-ID` header for resume from in-memory buffer.
 *
 * Phase 4: each user/assistant turn is also written to ocas before its SSE
 * event is emitted; the resulting hash is stamped onto the SSE payload's
 * `value.hash` and appended to `Session.turnHashes` so the history endpoint
 * can replay it.
 */

import type { IncomingMessage, ServerResponse } from "node:http";
import { SchemaValidationError } from "@ocas/core";
import type { Adapter, AgentResponse, Turn } from "@sumeru/core";
import { errorEnvelope } from "../envelope.js";
import { recordPayload } from "../ocas/index.js";
import type { SessionStore } from "../session/index.js";
import type { ServerConfig } from "../types.js";
import {
	appendEvent,
	createSseBufferStore,
	eventsAfter,
	formatEvent,
	lowestId,
	type SseBuffer,
	type SseBufferStore,
} from "./buffer.js";

export type MessageEndpointDeps = {
	sessions: SessionStore;
	adapters: Record<string, Adapter>;
	config: ServerConfig;
	bufferStore: SseBufferStore;
};

/** Build an isolated buffer store per server instance. */
export function makeMessageBufferStore(config: ServerConfig): SseBufferStore {
	return createSseBufferStore({
		maxSize: config.sseBufferSize,
		retentionMs: config.sseRetentionMs,
	});
}

/**
 * Result of parsing a Last-Event-ID header. The wire format is a non-negative
 * integer.
 */
type ParsedLastEventId =
	| { ok: true; value: number | null }
	| { ok: false; message: string };

function parseLastEventId(headerValue: string | undefined): ParsedLastEventId {
	if (headerValue === undefined) return { ok: true, value: null };
	const trimmed = headerValue.trim();
	if (trimmed === "") {
		return {
			ok: false,
			message: "Last-Event-ID header is present but empty",
		};
	}
	if (!/^[0-9]+$/.test(trimmed)) {
		return {
			ok: false,
			message: `Last-Event-ID must be a non-negative integer (got '${headerValue}')`,
		};
	}
	const n = Number.parseInt(trimmed, 10);
	if (!Number.isFinite(n) || n < 0) {
		return {
			ok: false,
			message: `Last-Event-ID must be a non-negative integer (got '${headerValue}')`,
		};
	}
	return { ok: true, value: n };
}

/**
 * Handle the SSE message endpoint. Performs body validation, status flips,
 * adapter invocation, and event emission.
 */
export async function handleMessageEndpoint(
	req: IncomingMessage,
	res: ServerResponse,
	gatewayName: string,
	sessionId: string,
	deps: MessageEndpointDeps,
): Promise<void> {
	const { sessions, adapters, config, bufferStore } = deps;

	bufferStore.purgeExpired(Date.now());

	const session = sessions.get(gatewayName, sessionId);
	if (session === null) {
		writeJson(
			res,
			404,
			errorEnvelope(
				"session_not_found",
				`Session ${sessionId} not found on gateway ${gatewayName}`,
			),
		);
		return;
	}
	if (session.status === "closed") {
		writeJson(
			res,
			404,
			errorEnvelope(
				"session_not_found",
				`Session ${sessionId} not found on gateway ${gatewayName}`,
			),
		);
		return;
	}

	const lastEventIdRaw = readHeader(req, "last-event-id");
	const lastEventId = parseLastEventId(lastEventIdRaw);
	if (!lastEventId.ok) {
		writeJson(
			res,
			400,
			errorEnvelope("invalid_last_event_id", lastEventId.message),
		);
		return;
	}

	const body = await readJsonBody(req);
	if (!body.ok) {
		writeJson(res, 400, errorEnvelope(body.error, body.message));
		return;
	}

	const isResumeOnly =
		lastEventId.value !== null && body.value.contentMissing === true;
	const isResumeWithBody =
		lastEventId.value !== null && body.value.contentMissing !== true;
	const lastEventIdValue = lastEventId.value;

	// Empty-body resume: pure replay
	if (isResumeOnly && lastEventIdValue !== null) {
		await handleResumeOnly(
			res,
			gatewayName,
			sessionId,
			lastEventIdValue,
			bufferStore,
		);
		return;
	}

	// Validate content: required for new send AND resume-with-body
	if (body.value.contentMissing === true) {
		writeJson(
			res,
			400,
			errorEnvelope("invalid_request", "Missing required field 'content'"),
		);
		return;
	}
	if (body.value.content === "") {
		writeJson(
			res,
			400,
			errorEnvelope(
				"invalid_request",
				"Field 'content' must be a non-empty string",
			),
		);
		return;
	}

	// Adapter is keyed by adapter NAME (from gateway config), not gateway name.
	const gatewayCfg = config.gateways[session.gateway];
	const adapterByName =
		gatewayCfg !== undefined ? adapters[gatewayCfg.adapter] : undefined;
	if (adapterByName === undefined) {
		writeJson(
			res,
			503,
			errorEnvelope(
				"adapter_unavailable",
				`Adapter '${gatewayCfg?.adapter ?? "(unknown)"}' is not registered for gateway '${session.gateway}'`,
			),
		);
		return;
	}

	// Resume-with-body: continue an existing buffer if one is live, else 404.
	if (isResumeWithBody && lastEventIdValue !== null) {
		const buf = bufferStore.getLatestForSession(gatewayName, sessionId);
		if (buf === null) {
			writeJson(
				res,
				404,
				errorEnvelope(
					"no_event_buffer",
					`No buffered SSE stream to resume on session ${sessionId}`,
				),
			);
			return;
		}
		await streamFromBufferThenLive(res, buf, lastEventIdValue, config);
		return;
	}

	// Concurrency check (idle → active). Resume cases handled above.
	const transition = sessions.tryActivate(gatewayName, sessionId);
	if (!transition.ok) {
		const reason = transition.reason;
		if (reason === "busy") {
			writeJson(
				res,
				409,
				errorEnvelope(
					"session_busy",
					`Session ${sessionId} is currently active`,
				),
			);
			return;
		}
		if (reason === "closed") {
			writeJson(
				res,
				404,
				errorEnvelope(
					"session_not_found",
					`Session ${sessionId} not found on gateway ${gatewayName}`,
				),
			);
			return;
		}
		writeJson(
			res,
			404,
			errorEnvelope(
				"session_not_found",
				`Session ${sessionId} not found on gateway ${gatewayName}`,
			),
		);
		return;
	}

	const nativeRef = sessions.getNativeRef(gatewayName, sessionId);
	if (nativeRef === null) {
		sessions.markIdle(gatewayName, sessionId);
		writeJson(
			res,
			503,
			errorEnvelope(
				"adapter_unavailable",
				`Session ${sessionId} has no native ref recorded — adapter likely failed at create time`,
			),
		);
		return;
	}

	// Write the user turn to ocas BEFORE invoking adapter.send. The session has
	// been activated; if the write fails we restore idle and return 500.
	const userTurnIndex = session.turnHashes.length;
	const userTurn: Turn = {
		index: userTurnIndex,
		role: "user",
		content: body.value.content,
		timestamp: new Date().toISOString(),
		toolCalls: null,
	};
	const userPayload = turnPayload(userTurn);
	let userHash: string;
	try {
		userHash = recordPayload(
			config.ocas.store,
			config.ocas.turnSchemaHash,
			userPayload,
		);
	} catch (err) {
		sessions.markIdle(gatewayName, sessionId);
		const cause = err instanceof Error ? err.message : String(err);
		const code =
			err instanceof SchemaValidationError
				? "ocas_validation_failed"
				: "ocas_write_failed";
		writeJson(
			res,
			500,
			errorEnvelope(
				code,
				`Failed to record user turn: ${truncate(cause, 500)}`,
			),
		);
		return;
	}
	// Phase 5: index the user turn for FTS5 search BEFORE appending the hash
	// or starting the SSE stream. If indexing fails the ocas write stays —
	// the index can be rebuilt — but the request fails fast.
	try {
		config.ocas.searchIndex.indexTurn({
			turnHash: userHash,
			sessionId,
			gateway: gatewayName,
			turnIndex: userTurn.index,
			role: "user",
			content: userTurn.content,
			createdAt: userTurn.timestamp,
		});
	} catch (err) {
		sessions.markIdle(gatewayName, sessionId);
		const cause = err instanceof Error ? err.message : String(err);
		writeJson(
			res,
			500,
			errorEnvelope(
				"search_index_failed",
				`Failed to update search index: ${truncate(cause, 500)}`,
			),
		);
		return;
	}
	sessions.appendTurnHash(gatewayName, sessionId, userHash);

	const buf = bufferStore.create(gatewayName, sessionId);
	writeSseHeaders(res);

	const startedAt = Date.now();
	const heartbeatTimer = startHeartbeats(res, buf, startedAt, config);

	let response: AgentResponse | null = null;
	let adapterError: Error | null = null;
	try {
		response = await adapterByName.send(nativeRef, body.value.content);
	} catch (err) {
		adapterError = err instanceof Error ? err : new Error(String(err));
	} finally {
		clearInterval(heartbeatTimer);
		sessions.markIdle(gatewayName, sessionId);
	}

	if (adapterError !== null) {
		const evt = appendEvent(
			buf,
			"error",
			JSON.stringify({
				type: "@sumeru/error",
				value: {
					error: "adapter_error",
					message: truncate(adapterError.message, 500),
				},
			}),
		);
		res.write(formatEvent(evt));
		bufferStore.finish(buf);
		res.end();
		return;
	}

	if (response !== null) {
		let validationFailure: { reason: string; message: string } | null = null;
		for (const turn of response.turns) {
			const payload = turnPayload(turn);
			let hash: string;
			try {
				hash = recordPayload(
					config.ocas.store,
					config.ocas.turnSchemaHash,
					payload,
				);
			} catch (err) {
				const cause = err instanceof Error ? err.message : String(err);
				validationFailure = {
					reason:
						err instanceof SchemaValidationError
							? "adapter_returned_invalid_turn"
							: "ocas_write_failed",
					message: truncate(cause, 500),
				};
				break;
			}
			// Phase 5: index the assistant turn. Failure here aborts the rest
			// of the response (the durable ocas write has already happened).
			try {
				config.ocas.searchIndex.indexTurn({
					turnHash: hash,
					sessionId,
					gateway: gatewayName,
					turnIndex: turn.index,
					role: turn.role,
					content: turn.content,
					createdAt: turn.timestamp,
				});
			} catch (err) {
				const cause = err instanceof Error ? err.message : String(err);
				validationFailure = {
					reason: "search_index_failed",
					message: `Failed to update search index: ${truncate(cause, 500)}`,
				};
				break;
			}
			sessions.appendTurnHash(gatewayName, sessionId, hash);
			const wireTurn: Turn = { ...turn, hash };
			const evt = appendEvent(
				buf,
				"turn",
				JSON.stringify({ type: "@sumeru/turn", value: wireTurn }),
			);
			res.write(formatEvent(evt));
		}
		if (validationFailure !== null) {
			const evt = appendEvent(
				buf,
				"error",
				JSON.stringify({
					type: "@sumeru/error",
					value: {
						error: validationFailure.reason,
						message: validationFailure.message,
					},
				}),
			);
			res.write(formatEvent(evt));
			bufferStore.finish(buf);
			res.end();
			return;
		}
		const summary = {
			turnCount: countEventsByType(buf, "turn"),
			tokens:
				response.tokens === null
					? null
					: { in: response.tokens.input, out: response.tokens.output },
			durationMs: response.durationMs,
		};
		const doneEvt = appendEvent(
			buf,
			"done",
			JSON.stringify({ type: "@sumeru/summary", value: summary }),
		);
		res.write(formatEvent(doneEvt));
	}

	bufferStore.finish(buf);
	res.end();
}

/**
 * Strip server-only / nullable fields from a Turn before recording so the
 * payload conforms to `@sumeru/turn`. The schema rejects extra fields
 * (`additionalProperties: false`); also drops `tokens` when null/absent and
 * `hash` (always server-injected, never persisted INSIDE the payload).
 */
function turnPayload(turn: Turn): Record<string, unknown> {
	const out: Record<string, unknown> = {
		index: turn.index,
		role: turn.role,
		content: turn.content,
		timestamp: turn.timestamp,
		toolCalls: turn.toolCalls,
	};
	if (turn.tokens !== undefined && turn.tokens !== null) {
		out.tokens = { input: turn.tokens.input, output: turn.tokens.output };
	}
	return out;
}

async function handleResumeOnly(
	res: ServerResponse,
	gatewayName: string,
	sessionId: string,
	since: number,
	bufferStore: SseBufferStore,
): Promise<void> {
	const buf = bufferStore.getLatestForSession(gatewayName, sessionId);
	if (buf === null) {
		writeJson(
			res,
			404,
			errorEnvelope(
				"no_event_buffer",
				`No buffered SSE stream to resume on session ${sessionId}`,
			),
		);
		return;
	}
	if (since > buf.maxId) {
		writeJson(
			res,
			400,
			errorEnvelope(
				"invalid_last_event_id",
				`Last-Event-ID ${since} is greater than the highest known event id ${buf.maxId}`,
			),
		);
		return;
	}
	if (buf.doneAt !== null && Date.now() - buf.doneAt > buf.maxSize * 0) {
		// retention check is handled by purgeExpired; if buf still resolves we can replay.
	}
	const lowest = lowestId(buf);
	if (lowest > 0 && since < lowest - 1) {
		writeJson(
			res,
			410,
			errorEnvelope(
				"events_evicted",
				`Last-Event-ID ${since} is older than the lowest still-buffered event ${lowest}`,
			),
		);
		return;
	}

	writeSseHeaders(res);
	const remaining = eventsAfter(buf, since);
	for (const evt of remaining) {
		res.write(formatEvent(evt));
	}
	res.end();
}

async function streamFromBufferThenLive(
	res: ServerResponse,
	buf: SseBuffer,
	since: number,
	_config: ServerConfig,
): Promise<void> {
	if (since > buf.maxId) {
		writeJson(
			res,
			400,
			errorEnvelope(
				"invalid_last_event_id",
				`Last-Event-ID ${since} is greater than the highest known event id ${buf.maxId}`,
			),
		);
		return;
	}
	const lowest = lowestId(buf);
	if (lowest > 0 && since < lowest - 1) {
		writeJson(
			res,
			410,
			errorEnvelope(
				"events_evicted",
				`Last-Event-ID ${since} is older than the lowest still-buffered event ${lowest}`,
			),
		);
		return;
	}

	writeSseHeaders(res);
	let cursor = since;
	const flushPending = (): boolean => {
		const events = eventsAfter(buf, cursor);
		for (const evt of events) {
			res.write(formatEvent(evt));
			cursor = Math.max(cursor, evt.id);
		}
		return buf.finished;
	};
	if (flushPending()) {
		res.end();
		return;
	}
	// Poll the buffer until finished. The original send writes events to this
	// same buffer; resume just mirrors them out on the new connection.
	await new Promise<void>((resolve) => {
		const poll = setInterval(() => {
			const finished = flushPending();
			if (finished) {
				clearInterval(poll);
				res.end();
				resolve();
			}
		}, 25);
		res.once("close", () => {
			clearInterval(poll);
			resolve();
		});
	});
}

function writeSseHeaders(res: ServerResponse): void {
	res.statusCode = 200;
	res.setHeader("Content-Type", "text/event-stream; charset=utf-8");
	res.setHeader("Cache-Control", "no-cache, no-transform");
	res.setHeader("Connection", "keep-alive");
	res.setHeader("X-Accel-Buffering", "no");
	res.flushHeaders?.();
}

function startHeartbeats(
	res: ServerResponse,
	buf: SseBuffer,
	startedAt: number,
	config: ServerConfig,
): NodeJS.Timeout {
	const timer = setInterval(
		() => {
			const elapsed = Date.now() - startedAt;
			const evt = appendEvent(
				buf,
				"heartbeat",
				JSON.stringify({
					type: "@sumeru/heartbeat",
					value: { elapsed },
				}),
			);
			res.write(formatEvent(evt));
		},
		Math.max(50, config.sseHeartbeatMs),
	);
	timer.unref();
	return timer;
}

function countEventsByType(buf: SseBuffer, event: string): number {
	let n = 0;
	for (const e of buf.events) {
		if (e.event === event) n += 1;
	}
	return n;
}

function truncate(s: string, max: number): string {
	if (s.length <= max) return s;
	return `${s.slice(0, max - 1)}…`;
}

function readHeader(req: IncomingMessage, name: string): string | undefined {
	const value = req.headers[name];
	if (value === undefined) return undefined;
	if (Array.isArray(value)) return value[0];
	return value;
}

type BodyParseResult =
	| {
			ok: true;
			value: { content: string; contentMissing: boolean };
	  }
	| { ok: false; error: string; message: string };

async function readJsonBody(req: IncomingMessage): Promise<BodyParseResult> {
	const chunks: Buffer[] = [];
	let total = 0;
	const MAX = 1024 * 1024;
	for await (const chunk of req) {
		const buf = chunk instanceof Buffer ? chunk : Buffer.from(chunk as string);
		total += buf.length;
		if (total > MAX) {
			return {
				ok: false,
				error: "invalid_request",
				message: "Request body too large",
			};
		}
		chunks.push(buf);
	}
	const raw = Buffer.concat(chunks).toString("utf-8").trim();
	if (raw.length === 0) {
		return { ok: true, value: { content: "", contentMissing: true } };
	}
	let parsed: unknown;
	try {
		parsed = JSON.parse(raw);
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err);
		return {
			ok: false,
			error: "invalid_json",
			message: `Request body is not valid JSON: ${detail}`,
		};
	}
	if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
		return {
			ok: false,
			error: "invalid_request",
			message: "Request body must be a JSON object",
		};
	}
	const obj = parsed as Record<string, unknown>;
	if (!("content" in obj)) {
		return { ok: true, value: { content: "", contentMissing: true } };
	}
	const content = obj.content;
	if (typeof content !== "string") {
		return {
			ok: false,
			error: "invalid_request",
			message: "Field 'content' must be a string",
		};
	}
	return { ok: true, value: { content, contentMissing: false } };
}

function writeJson(res: ServerResponse, status: number, body: unknown): void {
	const payload = JSON.stringify(body);
	res.statusCode = status;
	res.setHeader("Content-Type", "application/json; charset=utf-8");
	res.setHeader("Content-Length", Buffer.byteLength(payload).toString());
	res.end(payload);
}
